name: CI

on:
  workflow_dispatch:
  
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      
      - run: sudo apt -y install zip 

      - run: dotnet publish DotNetSql.Cli/DotNetSql.Cli.csproj -c Release -r osx.12-arm64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true --sc
      
      - run: dotnet publish DotNetSql.Cli/DotNetSql.Cli.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true --sc

      - run: zip sql-cli.win-x64.zip DotNetSql.Cli/bin/Release/net6.0/win-x64/publish/sql-cli.exe

      - name: Upload OSX ARM Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: DotNetSql.Cli/bin/Release/net6.0/osx.12-arm64/publish/sql-cli

      - name: Upload win-x64 Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: sql-cli.win-x64.zip
